### ISSUE TITLE
Specify default date/time format in UI

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/registry#272]
Currently they are as follows:

```
  time:
    formats:
      default: "%d. %B %Y, %H:%M"
      longer: "%a, %e. %b %Y, %H:%M"
      long: "%A, %e. %B %Y, %H:%M"
      short: "%d.%m.%y, %H:%M"
      shorts: "%d.%m.%y, %H:%M:%S"
      date: "%d.%m.%y"
      date_long: "%d. %B %Y"
      ydate: "%Y.%m.%d"
  date:
    formats:
      year_and_month: "%Y %B"
```

However, Timo mentioned other ones:

> "we use the standard date format for domain business. Again RFCs are a big help to get your head around the basics - please read. Example of the format is 2000-04-08T09:00:00.0Z. This is how we return data in EPP and this is how we tend to dipslay it in all of our interfaces. YYYY-MM-DD for date
> we have an idea of user specific settings in the portal for registrars where a user can set its local timezone and maybe even a different format"

I think we should clearly define the defaults for UI.
